### PR TITLE
add rkt pod listing support

### PR DESCRIPTION
**Pull request by tschuy**
Uses the rkt api, instead of trying to parse the output of `rkt list --full`, which means it's a lot nicer (except pulling in half of san francisco as a dependency).

### CODE REVIEW

**Comment by tschuy** [comment]
How would the "safe" pod be identified to mayday? Would we be best served by having a `pods: ["uuid1", "uuid2"]" section in our config? Set it on the CLI? (Neither of these seem particularly scalable/easy for the end user.) Collect from certain apps/when pods are running images from a given list (either in config, or hard coded, or passed as an arg/env variable)?

**Comment by tschuy** [comment]
For config, I think perhaps something like [viper](https://github.com/spf13/viper) might be better. It supports getting config vars from flags using pflags, and it might be possible to replace our config parsing logic with its logic. I'll try it out.

**Comment by tschuy** [comment]
I've not yet moved the `--danger` flag, but other than that, this should be mostly good to go.

**Comment by tschuy** [comment]
For that latest commit about errors, here's where I've decided to draw the line between "error" and "regular operation":

Error:
 - config reading failed (fatal)
 - couldn't collect journals
 - couldn't open file

Not Error:
 - couldn't open/connect to `rkt` (as this is standard fallback when not running mayday as root)
 - danger mode activated (user presumably knows what they're doing)
 - command running/timing out/returning non-zero exit code (exit code is swallowed)
 - errors closing zipfile (though they **are** fatal errors, meaning they call `os.Exit(1)`).

**Comment by tschuy** [comment]
Handy links for the diffs, skipping the vendor stuff: https://github.com/coreos/mayday/compare/ab64c55...6e3fa35
https://github.com/coreos/mayday/compare/05cd475...44ad3a4

**Comment by tschuy** [comment]
And I've also gotten docker support in there (https://github.com/tschuy/mayday/commit/ccc0f2889ceeaa81ecb616d7567309d24fcbff55) but we'll leave that for another PR :stuck_out_tongue_winking_eye:

**Comment by brianredbeard** [comment]
LGTM.

[LGTM](http://lgtm.in/i/MWngxwLYp)

**Pull request merged**
